version: 0.0
os: linux
files:
  - source: /
    destination: /home/node/node_app
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: node
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: node
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: node
